# -*- coding: utf-8 -*-
"""Cluster_DBSCAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDo-rDazRjE_zoqf_wt6U79sbrSK3OL_
"""

# Clusters con DBSCAN y Scikit-learn
# Solo es un Ejemplo porque no tenemos los datos de casas.csv

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

# Cargar datos
datos = np.loadtxt("/content/casas.csv", delimiter=";")

# Identificar Clusters
clusters = DBSCAN(eps=2, min_samples=10).fit_predict(datos)

print(clusters)

# Gráfica de matplotlib para mostrar los Clusters
plt.figure(figsize=(7.5, 7.5))
plt.scatter(datos[:, 0], datos[:, 1], c=clusters, s=100)
plt.xlabel('Antiguedad de la construcción en Años')
plt.ylabel('Precio de la Casa en Pesos (1:100,000)')
plt.box(False)
plt.show()

