# -*- coding: utf-8 -*-
"""Cross_validation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDo-rDazRjE_zoqf_wt6U79sbrSK3OL_
"""

# Evaluación de Modelos
# Validación Cruzada (Cross-validation)

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

personas = pd.read_csv("/content/salario.csv")

bosque = RandomForestClassifier()
bosque.fit(personas[['edad', 'estudio']].values, personas['ingreso'].values)

resultado = bosque.score(personas[['edad', 'estudio']].values, personas['ingreso'].values)

print(resultado)
print(cross_val_score(bosque, personas[['edad', 'estudio']].values, personas['ingreso'].values, cv=5).mean())