# -*- coding: utf-8 -*-
"""Regresion_lineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDo-rDazRjE_zoqf_wt6U79sbrSK3OL_
"""

# Contexto y Datos
import pandas as pd

datos = pd.read_csv('/content/ingreso.csv')

datos

# ==========================================================================

import matplotlib.pyplot as plt

plt.ylabel('Ingreso ($)')
plt.xlabel('Promedio de horas semanales trabajadas')
plt.scatter(datos['horas'], datos['ingreso'], color='pink')

plt.show()

# ==========================================================================

# Creación del Modelo de Regresión Lineal Simple
from sklearn import linear_model

regresion = linear_model.LinearRegression()

horas = datos['horas'].values.reshape((-1, 1))

modelo = regresion.fit(horas, datos['ingreso'])

print("Intersección (b)", modelo.intercept_)
print("Pendiente (m)", modelo.coef_)


entrada = [[39], [40], [43], [44]]
modelo.predict(entrada)

plt.scatter(entrada, modelo.predict(entrada), color='red')
plt.plot(entrada, modelo.predict(entrada), color='black')

plt.ylabel('Ingreso ($)')
plt.xlabel('Promedio de horas semanales trabajadas')
plt.scatter(datos['horas'], datos['ingreso'], color='pink')

plt.show()